### ISSUE TITLE
Can not run in sub directories

### ISSUE THREAD

**Issue by ederribeiro** [mkramb/bower-clean#1]
I have tried to clean subfolders, but without success, I've used the full path and still nothing.

example:

``` javascript
    "dependenciesIgnore": {
        "jquery": [
            "!**/jquery.min.js"
        ],
        "modernizr": [
            "!**/modernizr.js"
        ],
        "bootstrap": [
            "!**/dist/css/bootstrap.min.css",
            "!**/dist/css/bootstrap-theme.min.css",
            "!**/dist/js/bootstrap.min.js"
        ]
    }
```

When running this whole bootstrap folder is clean.

Am I doing something wrong? Thank you.

**Comment by mkramb** [comment]
Thanks for the bug report. Please update the package or source checkout. Will work now.
